# Generated by Django 4.2.23 on 2025-12-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_book_age_group_book_condition_book_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='book_title',
        ),
        migrations.AddField(
            model_name='donation',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
